language: node_js
node_js:
  - "node"
before_install:
  - npm install -g greenkeeper-lockfile
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
install: npm install
script:
  - npm run test
  
